export const TOGGLE_SHOW_WORKOUT = 'TOGGLE_SHOW_WORKOUT'
export const CONFIRM_IDENTITY = 'CONFIRM_IDENTITY'

export const FINISH_SET = 'FINISH_SET'
export const ADJUST_SET = 'ADJUST_SET'
export const GO_TO_SET = 'GO_TO_SET'

export const START_EXERCISE = 'START_EXERCISE'
export const FINISH_EXERCISE = 'FINISH_EXERCISE'
export const GO_TO_EXERCISE = 'GO_TO_EXERCISE'
export const NEXT_EXERCISE = 'NEXT_EXERCISE'
